-- Unique - to ensure that all values in a column are unique
-- NOT NULL - to ensure that all values in a column are not null
-- CHECK - to ensure that all values in a column meet a specific condition
-- DEFAULT - to set a default value for a column if no value is provided
-- Primary key
-- Auto increment (by default , applied based on logic)
CREATE TABLE student (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    age INT NOT check (age > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key
-- Unique and not null
-- Reference another table
-- Enforce referential integrity which prevents parent table/table data from being deleted if child table is not deleted
CREATE TABLE subjects (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    student_id INT,
    FOREIGN KEY (student_id) REFERENCES student(id)
);

-- Composite key
-- Combination of Mmltiple columns acts as a primary key
CREATE TABLE student_subjects_mapping (
    student_id INT,
    subject_id INT,
    is_active BOOLEAN,
    PRIMARY KEY (student_id, subject_id),
    FOREIGN KEY (student_id) REFERENCES student(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- Minimal -  A set of columns that is just sufficient to uniquely identify a row and has no unnecessary columns
-- Eg - In student_subjects_mapping , (student_id, subject_id) is a minimal key
-- Non minimal - A non-minimal key (superkey) uniquely identifies a row but contains extra unnecessary columns.
-- Eg - In student_subjects_mapping , (student_id, subject_id, is_active) is a non minimal key
-- Natural key - A key that comes from real-world data and is naturally unique.
-- Eg: email, phone number
-- Surrogate key - Key generated by the database with no business meaning (like auto increment id)
-- Eg: id (Primary key) generated by the database
-- Candidate key - A minimal set of columns that can uniquely identify a row.
-- Superkey - A minimal or non-minimal set of columns that can uniquely identify a row.